name: deploy
on: push
jobs:
    CopyRepository:
        runs-on: ubuntu-latest
        steps:
            - name: CheckoutCode
              uses: actions/checkout@v4 
            - name: RunDependency
              run: npm install





